import { useState, useEffect } from 'react';
import { ChevronLeft, Bell, Check, MessageCircle, MessageSquare, HelpCircle, UserPlus, Heart, CheckCheck } from 'lucide-react';
import { fetchNotifications, markNotificationRead, markAllNotificationsRead, type Notification } from '@/services/events';
import { useApp } from '@/hooks/useApp';
import type { ToastData } from '@/components/Toast';

interface NotificationsScreenProps { onBack: () => void; onToast: (toast: Omit<ToastData, 'id'>) => void; }

function getIcon(type: string) { switch (type) { case 'comment_reply': return MessageCircle; case 'new_comment': return MessageSquare; case 'new_question': return HelpCircle; case 'question_answered': return HelpCircle; case 'new_follower': return UserPlus; case 'invite_accepted': return Check; default: return Bell; } }
function getIconColor(type: string) { switch (type) { case 'comment_reply': return 'bg-blue-100 text-blue-600'; case 'new_comment': return 'bg-purple-100 text-purple-600'; case 'new_question': return 'bg-yellow-100 text-yellow-600'; case 'question_answered': return 'bg-green-100 text-green-600'; case 'new_follower': return 'bg-pink-100 text-pink-600'; default: return 'bg-gray-100 text-gray-600'; } }
function getActionLabel(type: string) { switch (type) { case 'comment_reply': return 'a répondu à votre commentaire'; case 'new_comment': return 'a commenté votre événement'; case 'new_question': return 'a posé une question'; case 'question_answered': return 'a répondu à votre question'; case 'new_follower': return 'a commencé à vous suivre'; case 'invite_accepted': return 'a accepté votre invitation'; default: return ''; } }

export function NotificationsScreen({ onBack, onToast }: NotificationsScreenProps) {
  const { user } = useApp();
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { if (!user) return; fetchNotifications(user.id).then(setNotifications).catch(() => onToast({ message: 'Erreur de chargement', type: 'error' })).finally(() => setLoading(false)); }, [user]);
  const handleMarkRead = async (id: string) => { try { await markNotificationRead(id); setNotifications(notifications.map((n) => n.id === id ? { ...n, is_read: true } : n)); } catch { onToast({ message: 'Erreur', type: 'error' }); } };
  const handleMarkAllRead = async () => { if (!user) return; try { await markAllNotificationsRead(user.id); setNotifications(notifications.map((n) => ({ ...n, is_read: true }))); onToast({ message: 'Tout marqué comme lu', type: 'success' }); } catch { onToast({ message: 'Erreur', type: 'error' }); } };
  const unreadCount = notifications.filter((n) => !n.is_read).length;
  return (
    <div className="min-h-screen bg-[#EDE8FF]">
      <div className="sticky top-0 z-20 bg-white/80 backdrop-blur-xl border-b border-gray-100"><div className="max-w-md mx-auto px-5 py-4 flex items-center justify-between"><button onClick={onBack} className="w-10 h-10 rounded-full bg-gray-100 flex items-center justify-center active:scale-90 transition-transform"><ChevronLeft className="w-5 h-5 text-[#1A1A2E]" /></button><div className="flex items-center gap-2"><Bell className="w-5 h-5 text-[#6600FF]" /><h1 className="text-lg font-extrabold text-[#1A1A2E]">Notifications</h1>{unreadCount > 0 && <span className="px-2 py-0.5 rounded-full bg-[#6600FF] text-white text-xs font-bold">{unreadCount}</span>}</div>{unreadCount > 0 ? (<button onClick={handleMarkAllRead} className="flex items-center gap-1 text-xs font-semibold text-[#6600FF] active:scale-95 transition-transform"><CheckCheck className="w-4 h-4" /> Tout lire</button>) : (<div className="w-10" />)}</div></div>
      <div className="max-w-md mx-auto px-5 py-4">{loading ? (<div className="flex items-center justify-center py-16"><div className="w-8 h-8 rounded-full border-3 border-[#6600FF]/30 border-t-[#6600FF] animate-spin" /></div>) : notifications.length === 0 ? (<div className="flex flex-col items-center justify-center py-20"><div className="w-20 h-20 rounded-full bg-white shadow-sm flex items-center justify-center mb-4"><Bell className="w-10 h-10 text-gray-300" /></div><p className="text-base font-bold text-[#1A1A2E] mb-1">Aucune notification</p><p className="text-sm text-gray-500 text-center max-w-xs">Vos notifications apparaîtront ici quand quelqu'un commentera vos événements, répondra à vos questions ou vous suivra.</p></div>) : (<div className="space-y-2">{notifications.map((n) => { const Icon = getIcon(n.type); const actionLabel = getActionLabel(n.type); return (<div key={n.id} onClick={() => { if (!n.is_read) handleMarkRead(n.id); }} className={`flex items-start gap-3 p-4 rounded-3xl cursor-pointer transition-all active:scale-[0.98] ${n.is_read ? 'bg-white' : 'bg-white shadow-md ring-1 ring-[#6600FF]/10'}`}><div className={`w-11 h-11 rounded-2xl flex items-center justify-center shrink-0 ${getIconColor(n.type)}`}><Icon className="w-5 h-5" /></div><div className="flex-1 min-w-0"><div className="flex items-center gap-2">{n.actor && <span className="text-sm font-bold text-[#1A1A2E] truncate">{n.actor.name}</span>}{actionLabel && <span className="text-xs text-gray-500 truncate">{actionLabel}</span>}</div><p className="text-sm text-gray-700 mt-0.5">{n.title}</p>{n.body && <p className="text-xs text-gray-500 mt-1 line-clamp-2">{n.body}</p>}<p className="text-[10px] text-gray-400 mt-1.5">{new Date(n.created_at).toLocaleString('fr-FR', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</p></div>{!n.is_read && <div className="w-2.5 h-2.5 rounded-full bg-[#6600FF] shrink-0 mt-2 animate-pulse" />}</div>); })}</div>)}</div>
    </div>
  );
}
