import { useState, useEffect } from 'react';
import { ChevronLeft, Building2, MapPin, BadgeCheck, Globe, Phone, Mail, Calendar, Users, Heart, Share2 } from 'lucide-react';
import { fetchOrganizationById, fetchEventsByOrganization, toggleOrganizationFollow, isFollowingOrganization } from '@/services/events';
import { useApp } from '@/hooks/useApp';
import { EventCard } from '@/components/EventCard';
import { EventCardSkeleton } from '@/components/Skeleton';
import type { Organization, Event } from '@/types';

interface OrganizerDetailScreenProps { organization: Organization; onBack: () => void; onEventClick: (event: Event) => void; onToast: (toast: { message: string; type: 'success' | 'error' | 'info' }) => void; }

export function OrganizerDetailScreen({ organization, onBack, onEventClick, onToast }: OrganizerDetailScreenProps) {
  const { user } = useApp();
  const [fullOrg, setFullOrg] = useState<Organization | null>(organization);
  const [events, setEvents] = useState<Event[]>([]);
  const [loading, setLoading] = useState(true);
  const [following, setFollowing] = useState(false);
  useEffect(() => { fetchOrganizationById(organization.id).then((data) => { if (data) setFullOrg(data); }); fetchEventsByOrganization(organization.id).then(setEvents).finally(() => setLoading(false)); if (user) isFollowingOrganization(organization.id, user.id).then(setFollowing); }, [organization.id, user]);
  const handleFollow = async () => { if (!user) { onToast({ message: 'Connectez-vous pour suivre', type: 'info' }); return; } const isFollowing = await toggleOrganizationFollow(organization.id, user.id); setFollowing(isFollowing); onToast({ message: isFollowing ? 'Abonné' : 'Désabonné', type: 'success' }); };
  const displayOrg = fullOrg || organization;
  return (
    <div className="min-h-screen pb-24">
      <div className="relative h-48 overflow-hidden">{displayOrg.cover_url ? <img src={displayOrg.cover_url} alt="" className="w-full h-full object-cover" /> : <div className="w-full h-full bg-gradient-to-br from-[#6600FF] to-[#9D4EDD]" />}<div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent" /><button onClick={onBack} className="absolute top-4 left-4 w-10 h-10 rounded-full bg-white/90 backdrop-blur flex items-center justify-center shadow-md active:scale-90 transition-transform"><ChevronLeft className="w-5 h-5 text-[#1A1A2E]" /></button><div className="absolute top-4 right-4 flex gap-2"><button onClick={handleFollow} className="w-10 h-10 rounded-full bg-white/90 backdrop-blur flex items-center justify-center shadow-md active:scale-90 transition-transform"><Heart className={`w-5 h-5 ${following ? 'text-red-500 fill-red-500' : 'text-[#1A1A2E]'}`} /></button><button className="w-10 h-10 rounded-full bg-white/90 backdrop-blur flex items-center justify-center shadow-md active:scale-90 transition-transform"><Share2 className="w-5 h-5 text-[#1A1A2E]" /></button></div></div>
      <div className="px-5 -mt-12 relative"><div className="flex items-end gap-4"><div className="w-20 h-20 rounded-2xl bg-white shadow-lg flex items-center justify-center overflow-hidden shrink-0">{displayOrg.logo_url ? <img src={displayOrg.logo_url} alt="" className="w-full h-full object-cover" /> : <Building2 className="w-8 h-8 text-[#6600FF]" />}</div><div className="flex-1 pb-1"><div className="flex items-center gap-1.5"><h1 className="text-xl font-extrabold text-[#1A1A2E]">{displayOrg.name}</h1>{displayOrg.verification_status === 'verified' && <BadgeCheck className="w-5 h-5 text-[#6600FF]" />}</div><div className="flex items-center gap-1 text-xs text-gray-500 mt-0.5"><MapPin className="w-3 h-3" /> {displayOrg.city}, {displayOrg.country}</div></div></div><div className="flex gap-4 mt-4"><div className="flex items-center gap-1.5"><Users className="w-4 h-4 text-[#6600FF]" /><span className="text-sm font-bold text-[#1A1A2E]">{displayOrg.followers_count}</span><span className="text-xs text-gray-500">abonnés</span></div><div className="flex items-center gap-1.5"><Calendar className="w-4 h-4 text-[#6600FF]" /><span className="text-sm font-bold text-[#1A1A2E]">{displayOrg.events_count}</span><span className="text-xs text-gray-500">événements</span></div></div><button onClick={handleFollow} className={`w-full mt-4 py-3.5 rounded-full font-bold transition-all ${following ? 'bg-white text-[#6600FF] shadow-sm' : 'btn-purple'}`}>{following ? 'Abonné' : 'Suivre'}</button>{displayOrg.description && <p className="mt-4 text-sm text-gray-600 leading-relaxed">{displayOrg.description}</p>}<div className="flex gap-3 mt-4">{displayOrg.website && <a href={displayOrg.website} target="_blank" rel="noopener noreferrer" className="w-10 h-10 rounded-full bg-white shadow-sm flex items-center justify-center active:scale-90 transition-transform"><Globe className="w-4 h-4 text-[#6600FF]" /></a>}{displayOrg.phone && <a href={`tel:${displayOrg.phone}`} className="w-10 h-10 rounded-full bg-white shadow-sm flex items-center justify-center active:scale-90 transition-transform"><Phone className="w-4 h-4 text-[#6600FF]" /></a>}{displayOrg.email && <a href={`mailto:${displayOrg.email}`} className="w-10 h-10 rounded-full bg-white shadow-sm flex items-center justify-center active:scale-90 transition-transform"><Mail className="w-4 h-4 text-[#6600FF]" /></a>}</div></div>
      <div className="px-5 mt-8"><h2 className="text-lg font-extrabold text-[#1A1A2E] mb-4">Événements</h2>{loading ? (<div className="space-y-3">{[1, 2, 3].map((i) => <EventCardSkeleton key={i} />)}</div>) : events.length > 0 ? (<div className="space-y-3">{events.map((event) => <EventCard key={event.id} event={event} onClick={() => onEventClick(event)} />)}</div>) : (<p className="text-sm text-gray-400 text-center py-8">Aucun événement publié pour le moment.</p>)}</div>
    </div>
  );
}
